### ISSUE TITLE
DataParallel not surport peft?

### ISSUE THREAD

**Issue by lehaoqu** [jakob949/Transformer_DB_Curation_MIBiG#1]
Hi
I try to use DataParallel on peft model like you
But get error: tensor don't on the same device

If don't use get_peft_model, the code can run

Can you help me?

![image](https://github.com/jakob949/Curation_of_MIBiG_DB_using_NLP/assets/74954167/9f82bfb1-23f0-47d4-866e-78a9da4ea570)

**Comment by jakob949** [comment]
Hi, 

I've just updated the T5.py script to use PyTorch DP and PEFT.  

Cheers
